#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mydb")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void Insertuserinfo(userinfo instance);
    partial void Updateuserinfo(userinfo instance);
    partial void Deleteuserinfo(userinfo instance);
    partial void InsertUser登入(User登入 instance);
    partial void UpdateUser登入(User登入 instance);
    partial void DeleteUser登入(User登入 instance);
    partial void Insertproductinfo(productinfo instance);
    partial void Updateproductinfo(productinfo instance);
    partial void Deleteproductinfo(productinfo instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::WindowsFormsApp1.Properties.Settings.Default.mydbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<userinfo> userinfo
		{
			get
			{
				return this.GetTable<userinfo>();
			}
		}
		
		public System.Data.Linq.Table<User登入> User登入
		{
			get
			{
				return this.GetTable<User登入>();
			}
		}
		
		public System.Data.Linq.Table<productinfo> productinfo
		{
			get
			{
				return this.GetTable<productinfo>();
			}
		}
		
		public System.Data.Linq.Table<productimage> productimage
		{
			get
			{
				return this.GetTable<productimage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userinfo")]
	public partial class userinfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _userid;
		
		private string _user姓名;
		
		private string _user電話;
		
		private string _user電子郵件;
		
		private System.Nullable<System.DateTime> _user出生日期;
		
		private System.Nullable<char> _user性別;
		
		private System.Nullable<int> _user身分;
		
		private EntityRef<User登入> _User登入;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void Onuser姓名Changing(string value);
    partial void Onuser姓名Changed();
    partial void Onuser電話Changing(string value);
    partial void Onuser電話Changed();
    partial void Onuser電子郵件Changing(string value);
    partial void Onuser電子郵件Changed();
    partial void Onuser出生日期Changing(System.Nullable<System.DateTime> value);
    partial void Onuser出生日期Changed();
    partial void Onuser性別Changing(System.Nullable<char> value);
    partial void Onuser性別Changed();
    partial void Onuser身分Changing(System.Nullable<int> value);
    partial void Onuser身分Changed();
    #endregion
		
		public userinfo()
		{
			this._User登入 = default(EntityRef<User登入>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user姓名", DbType="NVarChar(50)")]
		public string user姓名
		{
			get
			{
				return this._user姓名;
			}
			set
			{
				if ((this._user姓名 != value))
				{
					this.Onuser姓名Changing(value);
					this.SendPropertyChanging();
					this._user姓名 = value;
					this.SendPropertyChanged("user姓名");
					this.Onuser姓名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user電話", DbType="NVarChar(50)")]
		public string user電話
		{
			get
			{
				return this._user電話;
			}
			set
			{
				if ((this._user電話 != value))
				{
					this.Onuser電話Changing(value);
					this.SendPropertyChanging();
					this._user電話 = value;
					this.SendPropertyChanged("user電話");
					this.Onuser電話Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user電子郵件", DbType="NVarChar(50)")]
		public string user電子郵件
		{
			get
			{
				return this._user電子郵件;
			}
			set
			{
				if ((this._user電子郵件 != value))
				{
					this.Onuser電子郵件Changing(value);
					this.SendPropertyChanging();
					this._user電子郵件 = value;
					this.SendPropertyChanged("user電子郵件");
					this.Onuser電子郵件Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user出生日期", DbType="Date")]
		public System.Nullable<System.DateTime> user出生日期
		{
			get
			{
				return this._user出生日期;
			}
			set
			{
				if ((this._user出生日期 != value))
				{
					this.Onuser出生日期Changing(value);
					this.SendPropertyChanging();
					this._user出生日期 = value;
					this.SendPropertyChanged("user出生日期");
					this.Onuser出生日期Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user性別", DbType="Char(1)")]
		public System.Nullable<char> user性別
		{
			get
			{
				return this._user性別;
			}
			set
			{
				if ((this._user性別 != value))
				{
					this.Onuser性別Changing(value);
					this.SendPropertyChanging();
					this._user性別 = value;
					this.SendPropertyChanged("user性別");
					this.Onuser性別Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user身分", DbType="Int")]
		public System.Nullable<int> user身分
		{
			get
			{
				return this._user身分;
			}
			set
			{
				if ((this._user身分 != value))
				{
					this.Onuser身分Changing(value);
					this.SendPropertyChanging();
					this._user身分 = value;
					this.SendPropertyChanged("user身分");
					this.Onuser身分Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="userinfo_User登入", Storage="_User登入", ThisKey="userid", OtherKey="userid", IsUnique=true, IsForeignKey=false)]
		public User登入 User登入
		{
			get
			{
				return this._User登入.Entity;
			}
			set
			{
				User登入 previousValue = this._User登入.Entity;
				if (((previousValue != value) 
							|| (this._User登入.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User登入.Entity = null;
						previousValue.userinfo = null;
					}
					this._User登入.Entity = value;
					if ((value != null))
					{
						value.userinfo = this;
					}
					this.SendPropertyChanged("User登入");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User登入")]
	public partial class User登入 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _userid;
		
		private string _UserName;
		
		private string _Password;
		
		private EntityRef<userinfo> _userinfo;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public User登入()
		{
			this._userinfo = default(EntityRef<userinfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					if (this._userinfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="userinfo_User登入", Storage="_userinfo", ThisKey="userid", OtherKey="userid", IsForeignKey=true)]
		public userinfo userinfo
		{
			get
			{
				return this._userinfo.Entity;
			}
			set
			{
				userinfo previousValue = this._userinfo.Entity;
				if (((previousValue != value) 
							|| (this._userinfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._userinfo.Entity = null;
						previousValue.User登入 = null;
					}
					this._userinfo.Entity = value;
					if ((value != null))
					{
						value.User登入 = this;
						this._userid = value.userid;
					}
					else
					{
						this._userid = default(int);
					}
					this.SendPropertyChanged("userinfo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.productinfo")]
	public partial class productinfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _productid;
		
		private string _productname;
		
		private System.Nullable<int> _productprice;
		
		private System.Nullable<int> _productstock;
		
		private System.Nullable<int> _productpurchaseprice;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnproductidChanging(int value);
    partial void OnproductidChanged();
    partial void OnproductnameChanging(string value);
    partial void OnproductnameChanged();
    partial void OnproductpriceChanging(System.Nullable<int> value);
    partial void OnproductpriceChanged();
    partial void OnproductstockChanging(System.Nullable<int> value);
    partial void OnproductstockChanged();
    partial void OnproductpurchasepriceChanging(System.Nullable<int> value);
    partial void OnproductpurchasepriceChanged();
    #endregion
		
		public productinfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int productid
		{
			get
			{
				return this._productid;
			}
			set
			{
				if ((this._productid != value))
				{
					this.OnproductidChanging(value);
					this.SendPropertyChanging();
					this._productid = value;
					this.SendPropertyChanged("productid");
					this.OnproductidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productname", DbType="NVarChar(50)")]
		public string productname
		{
			get
			{
				return this._productname;
			}
			set
			{
				if ((this._productname != value))
				{
					this.OnproductnameChanging(value);
					this.SendPropertyChanging();
					this._productname = value;
					this.SendPropertyChanged("productname");
					this.OnproductnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productprice", DbType="Int")]
		public System.Nullable<int> productprice
		{
			get
			{
				return this._productprice;
			}
			set
			{
				if ((this._productprice != value))
				{
					this.OnproductpriceChanging(value);
					this.SendPropertyChanging();
					this._productprice = value;
					this.SendPropertyChanged("productprice");
					this.OnproductpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productstock", DbType="Int")]
		public System.Nullable<int> productstock
		{
			get
			{
				return this._productstock;
			}
			set
			{
				if ((this._productstock != value))
				{
					this.OnproductstockChanging(value);
					this.SendPropertyChanging();
					this._productstock = value;
					this.SendPropertyChanged("productstock");
					this.OnproductstockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productpurchaseprice", DbType="Int")]
		public System.Nullable<int> productpurchaseprice
		{
			get
			{
				return this._productpurchaseprice;
			}
			set
			{
				if ((this._productpurchaseprice != value))
				{
					this.OnproductpurchasepriceChanging(value);
					this.SendPropertyChanging();
					this._productpurchaseprice = value;
					this.SendPropertyChanged("productpurchaseprice");
					this.OnproductpurchasepriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.productimage")]
	public partial class productimage
	{
		
		private System.Nullable<int> _productid;
		
		private string _image;
		
		public productimage()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productid", DbType="Int")]
		public System.Nullable<int> productid
		{
			get
			{
				return this._productid;
			}
			set
			{
				if ((this._productid != value))
				{
					this._productid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(50)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this._image = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
